# https://crates.io/crates/cargo-audit
name: Security audit
on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * 1' # every monday at 10:00 UTC
permissions:
  issues: write
  checks: write
jobs:
  audit:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: Swatinem/rust-cache@v2
      - name: Install cargo-nextest
        run: cargo install cargo-audit --locked
      - uses: actions-rs/cargo@v1
        with:
          command: audit
