# https://crates.io/crates/cargo-audit
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          sed -i 's/components.*/components = []/' rust-toolchain
          echo 'profile = "minimal"' >> rust-toolchain
      - uses: rustsec/audit-check@v1.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
